Repository milieuinfo/webcomponent-vl-ui-action-group, pull requests merged in 2020-01, with the labels that each got.

#56 Update vl-ui-util
  bamboo-specs/bamboo.yml
  demo/demo.css
  demo/demo.js
  package-lock.json
  package.json
  style.css
  test/docker-compose.yml
  wct.docker.conf.json
  wct.local.conf.json
Labels: maintenance

#57 Update naar laatste util
  package-lock.json
  package.json
Labels: bugfix

#59 Verwijder pretest fase (installeren chromedriver). Deze komt via vl-ui-util binnen
  package.json
Labels: chore

#58 Overbodig NPM release import scripts verwijderd
  package.json
  vl-action-group.js
Labels: maintenance

#60 Update vl-ui-util
  demo/demo.css
  package-lock.json
  package.json
  style.css
  test/docker-compose.yml
Labels: maintenance

#61 Update vl-ui-util
  bamboo-specs/bamboo.yml
  package-lock.json
  package.json
  test/docker-compose.yml
Labels: maintenance

#62 Update vl-ui-util
  bamboo-specs/bamboo.yml
  docker-compose-release.yml
  package-lock.json
  package.json
Labels: maintenance
