Repository milieuinfo/webcomponent-vl-ui-action-group, pull requests merged in 2020-04, with the labels that each got.

#77 Update vl-ui-util
  .mocharc.js
  bamboo-specs/bamboo.yml
  package-lock.json
  package.json
Labels: chore

#78 Update dependency @govflanders/vl-ui-action-group to v3.9.2
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#79 Update dependency @govflanders/vl-ui-button to v3.9.2
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#80 Update dependency @govflanders/vl-ui-link to v3.9.2
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#81 Update dependency @govflanders/vl-ui-util to v3.9.2
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#82 Oplossing voor foutief export pad
  src/index.js
Labels: bug
